### ISSUE TITLE
Dudaa?

### ISSUE THREAD

**Issue by CarenTicante** [francosorbello/chaeaparser#1]
Hola, te escribo porque estoy comenzando un trabajo relacionado con estilos de aprendizaje y me topé con tu proyecto, quisiera saber si de casualidad tienes datos recopilados? 

Yo debería de recopilarlos en escuelas pero debido a la contingencia no he podido hacerlo y estoy atorada por eso, no sé si puedas compartirme algunos jaja

Saludos!

**Comment by francosorbello** [comment]
Hola, desafortunadamente ya no tengo los datos.
Saludos.
